LDLIBS=-lSDL2 -lGL -lGLU -lm
BINARIES=main colored-cubes triangles triangles2 mandlebrot mandlebrot2 golden-spiral shader_toy shader_toy_triangle

all: main colored-cubes triangles triangles2 mandlebrot golden-spiral shader_toy shader_toy_triangle

main: main.c
	gcc $^ $(LDLIBS) -o $@

colored-cubes: colored-cubes.c
	gcc $^ $(LDLIBS) -o $@

# generated by copilot
triangles: triangles.c
	gcc $^ $(LDLIBS) -o $@
triangles2: triangles2.c
	gcc $^ $(LDLIBS) -o $@
mandlebrot: mandlebrot.c
	gcc $^ $(LDLIBS) -o $@
golden-spiral: golden-spiral.c
	gcc $^ $(LDLIBS) -o $@
shader_toy: shader_toy.c
	gcc $^ $(LDLIBS) -o $@
shader_toy_triangle: shader_toy_triangle.c
	gcc $^ $(LDLIBS) -o $@

clean:
	rm -fv $(BINARIES)

